### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#346]
@codecalm @dsznajder Today project not so "user friendly" and hard to integrated, i suggest a few steps to fix it:

- [ ] [Disqus](https://disqus.com/admin/create/) for demo sites
- [ ] Doc page with third-party libraries (link, brief, examples)
- [ ] Doc page with "file map" - derscription for folders/files:
* [pages](https://github.com/tabler/tabler/tree/dev/pages) - [page templates](https://jekyllrb.com/docs/pages/)
  * [_data](https://github.com/tabler/tabler/tree/dev/pages/_data) - [data files](https://jekyllrb.com/docs/datafiles/)
  * [_includes](https://github.com/tabler/tabler/tree/dev/pages/_includes) - [sub templates for pages](https://jekyllrb.com/docs/includes/)
    * [forms](https://github.com/tabler/tabler/blob/dev/pages/_includes/forms/) - [demo for elemens](https://preview-dev.tabler.io/form-elements.html)
       * [form-elements-1.html](https://github.com/tabler/tabler/blob/dev/pages/_includes/forms/form-elements-1.html) - base elements
- [ ]  Scaffold forms/grids/tables. CLI configurator or WYSIWYG editor (tinymce with element plugins) return/save source html code

**Comment by WinterSilence** [comment]
I can help with Disqus and WYSIWYG editor

**Comment by WinterSilence** [comment]
[Grid scaffolds](https://github.com/Frontwise/grid-editor)

**Comment by rjd22** [comment]
Closing this because other tickets cover parts of this ticket.
